star-history/star-history

src/getStarHistory.js

Fixed a minor error message typo.

Fixed an error-message typo

---

website/index.html
website/src/index.js

- Format HTML
- `github` -> `GitHub`
- Adjust the text when the access token is stored in local storage

UI Enhancement

---

website/index.html

Fixed a very minor spelling issue I happened to notice. "Build" is used
for the present tense ("I will build this"), and "built" is for the past
tense ("I built this").
It's one of those confusing language things 😅 The same applies to some
other verbs ending with a "d" by the way (send probably being the most
common).

Fix very minor spelling issue (build → built)

---

core/getStarHistory.js
website/src/draw.js
website/src/index.js

When a repo has no stars, the promise in getStarHistory returns empty resArray. This will result in an error with page infinitely loading.
By throwing the error and catching it in index.js, we catch the error and display a notie alert on the webpage.

Fix #75 Generate error message when repo has no stars

---

website/index.html
website/src/index.js

Added the functionality to export to CSV. Displays an extra button on the bottom right of the webpage which allows users to download the past dates and stars of the repos currently displayed on the page into a CSV file. The CSV file will be consisted of rows made up of "repo name", "dateTime", and "number of stars of the repo at that dateTime". 
Note: Open with Microsoft Excel for better readability, MacOS's numbers doesn't display data in the correct format.

Address Issue #58 Export CSV

---

src/components/RepoInputer.vue
src/store/index.ts

Autocomplete & toggle repo visibility

update inputer functions

---

src/components/RepoInputer.vue
src/components/StarChartViewer.vue

1. fix toggle repo visibility;
2. update share on twitter text;

fix toggle repo visibility

---

src/packages/xy-chart/index.ts
src/packages/xy-chart/utils/drawAxis.ts
src/packages/xy-chart/utils/drawLegend.ts
src/packages/xy-chart/utils/getFormatNumber.ts

Fix the chart legend bounding and hide the zero value in Y axios.

fix chart legend bounding and yaxis zero value

---

src/packages/xy-chart/index.ts
src/packages/xy-chart/utils/drawAxis.ts
src/packages/xy-chart/utils/drawLabels.ts

feat: offset Y label dynamically

---

src/packages/xy-chart/components/ToolTip.ts
src/packages/xy-chart/utils/drawAxis.ts
src/packages/xy-chart/utils/drawLabels.ts
src/packages/xy-chart/utils/drawLegend.ts

fix: legend bounding calc

---

package.json
src/components/GenerateEmbedCodeDialog.vue
src/components/Header.vue
src/components/RepoInputer.vue
src/components/StarChartViewer.vue
src/components/TokenSettingDialog.vue
src/main.ts
src/packages/xy-chart/utils/drawLegend.ts
src/store/index.ts
yarn.lock

**refactor: use pinia instead of vuex**
update: insert space in text and emoji
fix: adjust legend min-width

refactor: use pinia instead of vuex

---

.eslintrc.js
package.json
src/components/Header.vue
src/components/SubscribeSection.vue
src/css/index.css
src/helpers/api.ts
src/pages/404.vue
src/pages/Blog.vue
src/pages/BlogList.vue
src/router/index.ts
tailwind.config.js
yarn.lock

feat: blog page

---

src/App.vue
src/components/BytebaseBanner.vue
src/components/Charts/StarXYChart.vue
src/components/Dialog.vue
src/components/GenerateEmbedCodeDialog.vue
src/components/Header.vue
src/components/RepoInputer.vue
src/components/StarChartViewer.vue
src/components/SubscribeSection.vue
src/components/Toast.vue
src/components/TokenSettingDialog.vue
src/extension/Popup.vue
src/pages/404.vue
src/pages/Blog.vue
src/pages/BlogList.vue
src/pages/EmbedWebSite.vue
src/pages/Home.vue

Use `<script setup />`(same popular code style as main project `bytebase`) instead of `defineComponent`

refactor: vue code style with setup

---

package.json
scripts/emptyOutDir.ts
tsconfig.json
vite.config.ts
yarn.lock

The vite config `build.emptyOutDir` has an unwanted behavir in building, so that I have to write a script to control the empty out dir.

feat: update build scripts

---

src/extension/Popup.vue
src/extension/manifest.json

Refer docs: https://developer.chrome.com/docs/webstore/troubleshooting/#misunderstood-perms

fix: manifest permissions

---

src/helpers/api.ts

feat: reduce number of requests

---

packages/xy-chart/index.ts
server/cache.ts
server/const.ts
server/main.ts
server/utils.ts

* Change default chart width from 600px to 800px;
* More chart size can be set in URL: mobile 600px(width), laptop(default) 800px, desktop 1000px;

feat: multi svg size

---

packages/xy-chart/index.ts
server/main.ts
src/components/Charts/StarXYChart.vue
src/components/StarChartViewer.vue
src/pages/EmbedWebSite.vue

Fix styles which cause chart non-scrollable in mobile view.

fix: chart styles in mobile view

---

src/pages/DynamicPathMatcher.vue
src/router/index.ts

Redirect `/bytebase/star-history` to `/#bytebase/star-history`.

feat: dynamic path matcher

---

src/components/Charts/StarXYChart.vue
src/components/GenerateEmbedCodeDialog.vue
src/components/Header.vue
src/components/RepoInputer.vue
src/components/StarChartViewer.vue
src/components/TokenSettingDialog.vue
src/helpers/consts.ts
src/pages/EmbedWebSite.vue
tailwind.config.js

feat: suitable chart in mobile view

---

src/components/RepoInputer.vue

Fixes #158.
If there's anything else I need to do, I'd appreciate letting me know :)

Trim hashtag link

---

src/components/BytebaseBanner.vue
src/components/RepoInputer.vue

fix: banner padding in mobile view

---

common/utils.ts

Fix star data format with seconds to show those just created repo.

fix: star date format

---

src/components/SubscribeSection.vue

Update subscribe success message that we don't need the user to confirm subscription right now.

chore: update subscribe message

---

README.md

I took the **liberty** of making this README as good as my humanly eyes can see it as.
In other words, 'm spying on different README(s) I can **prettify**.

:art: Prettier README!

---

vite.config.ts

chore: let vite try another port while :3000 is occupied

---

src/components/BytebaseBanner.vue
src/components/StarChartViewer.vue

feat: show the sponsor banner when page is empty

---

src/components/StarChartViewer.vue

Our last ordering is the amount of repo stars. Now we change it to input order.

chore: update repo sort

---

index.html
src/components/RepoInputer.vue
src/components/StarChartViewer.vue

feat: add latest blog hint

---

src/components/StarChartViewer.vue

chore: remove showme how to add to github readme

---

src/components/BlogBanner.vue
src/components/RepoInputer.vue
src/pages/Blog.vue
src/pages/BlogList.vue
src/pages/Home.vue

chore: add hot blogs banner to left sidebar

---

src/components/HighlightBlogSection.vue
src/pages/Blog.vue
src/pages/BlogList.vue
src/pages/Home.vue

https://user-images.githubusercontent.com/24653555/217733651-38ac6bd4-50d9-4586-9e9d-478770159286.mp4

chore: update highlight blog section style

---

common/utils.ts
package.json
pnpm-lock.yaml
src/main.ts
src/pages/Blog.vue

feat: add dynamic meta for blog page

---

src/components/HighlightBlogSection.vue

chore: add collections

---

src/components/Header.vue

fix: header response style

---

public/blog/data.json

update the featured post, cc @tianzhou

docs: update featured post

---

src/components/RepoInputer.vue

chore: add external link to repo name

---

packages/xy-chart/index.ts
packages/xy-chart/utils/drawWatermark.ts
src/components/Charts/StarXYChart.vue
src/components/StarChartViewer.vue

feat: draw watermark in XYChart

---

pnpm-lock.yaml
server/main.ts
server/package.json
server/pnpm-lock.yaml

* update pnpm lock file;
* add copyfiles to dist;

chore: add copyfiles to dist

---

packages/xy-chart/index.ts
server/main.ts
src/components/EmbedMarkdownSection.vue

feat: dark mode option

---

src/components/EmbedMarkdownSection.vue

We should keep it as simple as possible.

chore: update embed code

---

src/components/EmbedMarkdownSection.vue

Fix https://github.com/star-history/star-history/pull/323#issuecomment-1568411210

feat: add button for dark mode

---

src/pages/BlogList.vue

[#336](https://github.com/star-history/star-history/issues/336)

fix: website blog page error

---

public/blog/mockoon.md

docs: fix mockoon image

---

public/blog/chatgpt-js.md

docs: fix chatgpt.js post

---

public/blog/cli-tool-for-llm.md

docs: fix typos

---

public/blog/wasp.md

docs: fix wasp code snippet

---

.gitignore
packages/xy-chart/index.ts
server/main.ts
src/components/Charts/StarXYChart.vue

**Context:** Allow custom background color more easily, when embedding an iframe.

feat: add transparent option

---

public/blog/data.json

docs: fix proton snippet

---

src/components/EmbedMarkdownSection.vue

should resolve https://github.com/star-history/star-history/issues/376

fix: url-encoding

---

public/blog/list-your-open-source-project.md

docs: fix typo

---

public/blog/text2sql.md

chores: fix text2sql

---

components/footer.tsx

docs: fix link

---

helpers/blog.json

docs: fix paradedb author

---

public/blog/ai-web-scraper.md

fix typos in ai web scrapers piece

---

public/blog/ai-web-scraper.md

fix images

---

public/blog/rag-frameworks.md

August Edition update
